# Generated by Django 2.1.2 on 2018-10-15 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chaves', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chave',
            old_name='owner',
            new_name='dono',
        ),
    ]
