# Generated by Django 2.1.2 on 2018-12-03 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chaves', '0002_auto_20181014_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='chave',
            name='ultimaOperacao',
            field=models.TextField(default='Nao existem operacoes no historico'),
            preserve_default=False,
        ),
    ]
